import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

import { ThemeContextProvider } from "@/contexts/ThemeContextProvider";
import TopNavigation from "@/components/TopNavigation";
import SideNavigation from "@/components/SideNavigation";

const plus_Jakarta_Sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body
          className={`dark:bg-kanbanDarkGreyBG bg-kanbanLightGreyBG font-medium${plus_Jakarta_Sans.className}`}
        >
          <div>
            <TopNavigation />
            <SideNavigation />
          </div>
          {children}
        </body>
      </ThemeContextProvider>
    </html>
  );
}
